# This is where we define how to set up a complete environment with
# several linked containers to serve the new and old sites with webservers
# and database servers.
version: '2'

services:
  drupal8:
    build:
      context: .
      dockerfile: Dockerfile-drupal8
    environment:
      DRUPAL_PROFILE: standard
      DRUPAL_SITE_NAME: Drupal
      DRUPAL_USER: admin
      DRUPAL_PASS: admin
      DRUPAL_DBURL: mysql://drupal:drupal@drupal8database:3306/drupal
    ports:
      - "80"
    volumes:
      # In order to migrate from Drupal 6, we need access to the entire Drupal 6
      # codebase. When importing, Drupal 8 assumes we a path to the root of
      # Drupal 6, which is why we need the directory structure
      # sites/default/files.
      - ./workspace/workspace/d6files:/drupal6code/sites/default/files
      - ./my_migration:/var/www/html/modules/custom/my_migration
    links:
      - drupal8database:drupal8database
      # In order to migrate from Drupal 6, we need access to the entire Drupal 6
      # database.
      - drupal6database:drupal6database
    working_dir: /var/www/html
    restart: always

  # Database Server
  drupal8database:
    image: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306"
    restart: always

  drupal6:
    build:
      context: .
      dockerfile: Dockerfile-drupal6
    environment:
      DRUPAL_PROFILE: standard
      DRUPAL_SITE_NAME: Drupal
      DRUPAL_USER: admin
      DRUPAL_PASS: admin
      DRUPAL_DBURL: mysql://drupal:drupal@drupal6database:3306/drupal
    ports:
      - "80"
    volumes:
      # Share the entire codebase with the Docker host, so it can in turn be
      # shard with the Drupal 8 container, which needs it for the migration.
      - ./workspace/workspace/d6files:/var/www/html/sites/default/files
    links:
      - drupal6database:drupal6database
    working_dir: /var/www/html
    restart: always

  # Database Server
  drupal6database:
    image: mysql
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306"
    restart: always
